# -*- coding: utf-8 -*-
"""pure pursuit problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cv4vfZdUeeegVcyOR4UsRE_-SFoUPQ9g
"""

import random
import math
flag = 0
vf = 20
time = 0

xf = random.randint(1,1000)
yf = random.randint(1,1000)
xb = random.randint(1,1000)
yb = random.randint(1,1000)

while flag == 0:
  distance = math.sqrt((xf-xb)**2 + (yf - yb)**2)

  if distance <= 100:
    print("The Bomber Plane Shot Down at time", time)
    flag = 1
  elif distance > 1000:
    print("The Bomber Plane Escape at time ",time)
    flag = 1
  else:
    xf = xf + vf*(xb-xf)/distance
    yf = yf + vf*(yb-yf)/distance
    xb = random.randint(1,1000)
    yb = random.randint(1,1000)
    time+=1